name: Static Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cppcheck and Flawfinder
      run: |
        sudo apt-get update
        sudo apt-get install cppcheck flawfinder -y

    - name: Run Cppcheck
      run: |
        cppcheck --enable=all --inconclusive --xml . 2> cppcheck-report.xml

    - name: Run Flawfinder
      run: |
        flawfinder . > flawfinder-report.txt

    - name: Upload Cppcheck report
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-report
        path: cppcheck-report.xml

    - name: Upload Flawfinder report
      uses: actions/upload-artifact@v4
      with:
        name: flawfinder-report
        path: flawfinder-report.txt
