name: Static Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cppcheck and Python modules
      run: |
        sudo apt-get update
        sudo apt-get install cppcheck python3-pip -y
        pip3 install pygments

    - name: Run Cppcheck (generate XML)
      run: |
        cppcheck --enable=all --xml --xml-version=2 . 2> cppcheck-report.xml

    - name: Generate HTML Report from XML
      run: |
        python3 /usr/share/cppcheck/htmlreport/cppcheck-htmlreport \
          --file=cppcheck-report.xml \
          --report-dir=cppcheck-html \
          --source-dir=. \
          --title="Cppcheck Static Analysis Report"

    - name: Upload HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-html
        path: cppcheck-html/
